#!/bin/bash

BF=sch2HdlBatchFile
TOP=comptest_n2
UCF=Nexys2_500General.ucf

function f1()
{
    >$BF
    for s in *.sch
    do
	v=$(echo $s|sed 's/sch$/vf/')
	echo 'sch2hdl,-family,spartan3e,-verilog,'$v',-w,'$s >>$BF
    done
}

function f2()
{
    xilinx.sh sch2hdl -batch $BF
}

function f3()
{
    mkdir -p xst/{dump.xst,projnav.tmp,work}
    xilinx.sh xst -intstyle ise -ifn "${TOP}.xst" -ofn "${TOP}.syr"
}

function f4()
{
    xilinx.sh ngdbuild -intstyle ise -dd _ngo -nt timestamp -uc $UCF -p xc3s500e-fg320-5 ${TOP}.ngc ${TOP}.ngd
}

function f5()
{
    xilinx.sh map -intstyle ise -p xc3s500e-fg320-5 -cm area -ir off -pr off -c 100 -o ${TOP}_map.ncd ${TOP}.ngd ${TOP}.pcf
}

function f6()
{
    xilinx.sh par -intstyle ise -w -ol std -t 1 ${TOP}_map.ncd ${TOP}.ncd ${TOP}.pcf
}

function f7()
{
    xilinx.sh trce -v 3 -s 5 -n 3 -fastpaths -xml ${TOP}.twx ${TOP}.ncd -o ${TOP}.twr ${TOP}.pcf -ucf ${UCF}
}

function f8()
{
    xilinx.sh bitgen -f ${TOP}.ut ${TOP}.ncd
}

#f1
#f2
f3
f4
f5
f6
f7
f8
