all:

clean:
	rm -rf *.cache
	rm -rf *.hw
	rm -rf *.runs
	rm -rf *.sim
	rm -rf *.ip_user_files
	rm -rf .Xil
	rm -rf *~

wcelan:
	del /f /s /q *.cache
	del /f /s /q *.hw
	del /f /s /q *.runs
	del /f /s /q *.sim
	del /f /s /q *.ip_user_files
	del /f /s /q .Xil
	del /f /q *~

